name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=19.0.3  
  - numpy=1.16.2
  - pip:
    - eli5==0.10.1
    - pyarrow==0.14.1    
    - keras==2.2.5
    - matplotlib==3.1.1
    - scikit-learn==0.21.3
    - seaborn==0.9.0
    - pandas==0.24.2
    - plotly==4.3.0
    - tensorflow-gpu==1.12.0
#comment out gpu version if u have to use cpu only
#   - tensorflow==1.12.0
    
